<?xml version="1.0" encoding="utf-8"?><Database Name="db_a7d8a5_pasantesecu911" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQL5105.site4now.net;Initial Catalog=db_a7d8a5_pasantesecu911;User ID=db_a7d8a5_pasantesecu911_admin" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="db_a7d8a5_pasantesecu911ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_Asistencia" Member="Tbl_Asistencia">
    <Type Name="Tbl_Asistencia">
      <Column Name="Asistencia_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Codigo_Pasante" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoraEntrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoraSalida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Actividades" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Usu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Usuarios_Tbl_Asistencia" Member="Tbl_Usuarios" ThisKey="Usu_id" OtherKey="Usu_id" Type="Tbl_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Usuarios" Member="Tbl_Usuarios">
    <Type Name="Tbl_Usuarios">
      <Column Name="Usu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Celular" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Token" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaToken" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Tusu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Usuarios_Tbl_Asistencia" Member="Tbl_Asistencia" ThisKey="Usu_id" OtherKey="Usu_id" Type="Tbl_Asistencia" />
      <Association Name="Tbl_Usuarios_Tbl_Pasantes" Member="Tbl_Pasantes" ThisKey="Usu_id" OtherKey="Usu_id" Type="Tbl_Pasantes" />
      <Association Name="Tbl_Usuarios_Tbl_Responsable" Member="Tbl_Responsable" ThisKey="Usu_id" OtherKey="Usu_id" Type="Tbl_Responsable" />
      <Association Name="Tbl_TipoUsuario_Tbl_Usuarios" Member="Tbl_TipoUsuario" ThisKey="Tusu_id" OtherKey="Tusu_id" Type="Tbl_TipoUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Horas" Member="Tbl_Horas">
    <Type Name="Tbl_Horas">
      <Column Name="Horas_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ConceptoH" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Labor_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Labores_Tbl_Horas" Member="Tbl_Labores" ThisKey="Labor_id" OtherKey="Labor_id" Type="Tbl_Labores" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Labores" Member="Tbl_Labores">
    <Type Name="Tbl_Labores">
      <Column Name="Labor_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Nhoras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pasantes_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Labores_Tbl_Horas" Member="Tbl_Horas" ThisKey="Labor_id" OtherKey="Labor_id" Type="Tbl_Horas" />
      <Association Name="Tbl_Pasantes_Tbl_Labores" Member="Tbl_Pasantes" ThisKey="Pasantes_id" OtherKey="Pasantes_id" Type="Tbl_Pasantes" IsForeignKey="true" />
      <Association Name="Tbl_Proyecto_Tbl_Labores" Member="Tbl_Proyecto" ThisKey="Proyecto_id" OtherKey="Proyecto_id" Type="Tbl_Proyecto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Pasantes" Member="Tbl_Pasantes">
    <Type Name="Tbl_Pasantes">
      <Column Name="Pasantes_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Carrera" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Curriculum" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Acuerdo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Nsemestre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Universidad" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Actividad" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Codigo_Pasante" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CodigoEcu" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Usu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Pasantes_Tbl_Labores" Member="Tbl_Labores" ThisKey="Pasantes_id" OtherKey="Pasantes_id" Type="Tbl_Labores" />
      <Association Name="Tbl_Usuarios_Tbl_Pasantes" Member="Tbl_Usuarios" ThisKey="Usu_id" OtherKey="Usu_id" Type="Tbl_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Proyecto" Member="Tbl_Proyecto">
    <Type Name="Tbl_Proyecto">
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Resp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Proyecto_Tbl_Labores" Member="Tbl_Labores" ThisKey="Proyecto_id" OtherKey="Proyecto_id" Type="Tbl_Labores" />
      <Association Name="Tbl_Responsable_Tbl_Proyecto" Member="Tbl_Responsable" ThisKey="Resp_id" OtherKey="Resp_id" Type="Tbl_Responsable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Responsable" Member="Tbl_Responsable">
    <Type Name="Tbl_Responsable">
      <Column Name="Resp_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Usu_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Responsable_Tbl_Proyecto" Member="Tbl_Proyecto" ThisKey="Resp_id" OtherKey="Resp_id" Type="Tbl_Proyecto" />
      <Association Name="Tbl_Usuarios_Tbl_Responsable" Member="Tbl_Usuarios" ThisKey="Usu_id" OtherKey="Usu_id" Type="Tbl_Usuarios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_TipoUsuario" Member="Tbl_TipoUsuario">
    <Type Name="Tbl_TipoUsuario">
      <Column Name="Tusu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Tbl_TipoUsuario_Tbl_Usuarios" Member="Tbl_Usuarios" ThisKey="Tusu_id" OtherKey="Tusu_id" Type="Tbl_Usuarios" />
    </Type>
  </Table>
  <Function Name="dbo.Actividades" Method="Actividades">
    <Parameter Name="cedula" Type="System.Int32" DbType="Int" />
    <ElementType Name="ActividadesResult">
      <Column Name="Cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Actividades" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UsuariosyResponsables" Method="UsuariosyResponsables">
    <ElementType Name="UsuariosyResponsablesResult">
      <Column Name="Usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Celular" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AcuerdoPasantes" Method="AcuerdoPasantes">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="AcuerdoPasantesResult">
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Universidad" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Actividad" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Carrera" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Asistencias" Method="Asistencias">
    <ElementType Name="AsistenciasResult">
      <Column Name="Asistencia_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pasante" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Codigo_Pasante" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HoraEntrada" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HoraSalida" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Actividades" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BuscarPorNumeroDeHoras" Method="BuscarPorNumeroDeHoras">
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="BuscarPorNumeroDeHorasResult">
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Nhoras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horasA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.horas" Method="horas">
    <ElementType Name="horasResult">
      <Column Name="Horas_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConceptoH" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pasante" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.labores" Method="labores">
    <ElementType Name="laboresResult">
      <Column Name="Labor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Pasante" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nhoras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LaboresPorPasante" Method="LaboresPorPasante">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="LaboresPorPasanteResult">
      <Column Name="Labor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Nhoras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pasantes_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NumeroDeHoras" Method="NumeroDeHoras">
    <ElementType Name="NumeroDeHorasResult">
      <Column Name="Pasante" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Nhoras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HorasA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NumeroDeHorasPasantes" Method="NumeroDeHorasPasantes">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="NumeroDeHorasPasantesResult">
      <Column Name="ConceptoL" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Nhoras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horasA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.pasantes" Method="pasantes">
    <ElementType Name="pasantesResult">
      <Column Name="Pasantes_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pasantes" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.proyectos" Method="proyectos">
    <ElementType Name="proyectosResult">
      <Column Name="Proyecto_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Responsable" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.responsables" Method="responsables">
    <ElementType Name="responsablesResult">
      <Column Name="Resp_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Responsables" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TotalPasantesActivos" Method="TotalPasantesActivos">
    <ElementType Name="TotalPasantesActivosResult">
      <Column Name="Activos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TotalPasantesInactivos" Method="TotalPasantesInactivos">
    <ElementType Name="TotalPasantesInactivosResult">
      <Column Name="Inactivos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TotalPasantesxCarrera" Method="TotalPasantesxCarrera">
    <ElementType Name="TotalPasantesxCarreraResult">
      <Column Name="TotalPasantes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Carrera" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TotalPasantesxUniversidad" Method="TotalPasantesxUniversidad">
    <ElementType Name="TotalPasantesxUniversidadResult">
      <Column Name="TotalPasantes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Universidad" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TotalResponsables" Method="TotalResponsables">
    <ElementType Name="TotalResponsablesResult">
      <Column Name="Responsables" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TotalUsuarios" Method="TotalUsuarios">
    <ElementType Name="TotalUsuariosResult">
      <Column Name="Usuarios" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UsuariosyPasantes" Method="UsuariosyPasantes">
    <ElementType Name="UsuariosyPasantesResult">
      <Column Name="Usu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cedula" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nombres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Celular" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Curriculum" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Acuerdo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Universidad" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Actividad" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Carrera" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nsemestre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Codigo_Pasante" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CodigoEcu" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>